# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUd27B3Gf5UgbJJEQD307IgZGhd311gZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score

# Download the dataset if not present!wget -nc https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Projects/master/Mall_Customers.csv


# 1. Load the Dataset
df = pd.read_csv('Mall_Customers.csv')

# 2. Data Pre-processing
# We focus on 'Annual Income' and 'Spending Score' to find profitable groups
X = df.iloc[:, [3, 4]].values

# Scaling the data (Standardization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Data Preparation (Train-Test Split)
# Note: Clustering is typically unsupervised, but we split to demonstrate the requested step.
X_train, X_test = train_test_split(X_scaled, test_size=0.2, random_state=42)

# --- Algorithm 1: K-Means Clustering ---
# Using the Elbow Method to find the optimal number of clusters
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(X_train)
    wcss.append(kmeans.inertia_)

# Visualization of Elbow Method
plt.figure(figsize=(10, 5))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method for K-Means')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

# Applying K-Means with optimal clusters (typically 5 for this dataset)
kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)
y_kmeans = kmeans.fit_predict(X_scaled)

# --- Algorithm 2: Agglomerative Clustering ---
agg_clustering = AgglomerativeClustering(n_clusters=5, linkage='ward')
y_agg = agg_clustering.fit_predict(X_scaled)

# 4. Model Evaluation
score_kmeans = silhouette_score(X_scaled, y_kmeans)
score_agg = silhouette_score(X_scaled, y_agg)

print(f"Silhouette Score for K-Means: {score_kmeans:.4f}")
print(f"Silhouette Score for Agglomerative: {score_agg:.4f}")

# 5. Visualizing the Clusters (K-Means Results)
plt.figure(figsize=(10, 7))
sns.scatterplot(x=X_scaled[:, 0], y=X_scaled[:, 1], hue=y_kmeans, palette='viridis', s=100)
plt.title('Customer Segments (K-Means)')
plt.xlabel('Annual Income (Scaled)')
plt.ylabel('Spending Score (Scaled)')
plt.legend(title='Cluster')
plt.show()

# Identifying "Profitable" Customers:
# High Income (Right side) + High Spending Score (Top side) = High Value Group
df['Cluster'] = y_kmeans
profitable_group = df[df['Cluster'] == 0] # Adjust index based on visual output
print("\n--- Sample of Profitable Customers (High Income, High Spend) ---")
print(profitable_group.head())