# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10A0mEDzIItxSmSlSXYFiM4a-DuChgvkh
"""

# ===============================
# 1. Import Libraries
# ===============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score, mean_squared_error

# ===============================
# 2. Load Dataset
# ===============================
df = pd.read_csv("uber.csv")

print("First 5 rows:\n", df.head())

# ===============================
# 3. Data Preprocessing
# ===============================

# Drop unnecessary column
df = df.drop(['Unnamed: 0', 'key'], axis=1, errors='ignore')

# Convert pickup_datetime to datetime
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'], errors='coerce')

# Extract useful features
df['hour'] = df['pickup_datetime'].dt.hour
df['day'] = df['pickup_datetime'].dt.day
df['month'] = df['pickup_datetime'].dt.month

# Drop original datetime
df = df.drop(['pickup_datetime'], axis=1)

# Handle missing values
df = df.dropna()

# Remove invalid passengers
df = df[df['passenger_count'] > 0]

print("\nAfter preprocessing:\n", df.head())

# ===============================
# 4. Outlier Detection
# ===============================

plt.figure()
sns.boxplot(y=df['fare_amount'])
plt.title("Boxplot of Fare Amount")
plt.show()

# Remove extreme outliers
df = df[(df['fare_amount'] > 0) & (df['fare_amount'] < 100)]

# ===============================
# 5. Correlation Check
# ===============================

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

# ===============================
# 6. Feature & Target Selection
# ===============================

X = df.drop('fare_amount', axis=1)
y = df['fare_amount']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ===============================
# 7. Linear Regression
# ===============================

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

# ===============================
# 8. Ridge Regression
# ===============================

ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)

# ===============================
# 9. Lasso Regression
# ===============================

lasso = Lasso(alpha=0.1)
lasso.fit(X_train, y_train)

y_pred_lasso = lasso.predict(X_test)

# ===============================
# 10. Evaluation Function
# ===============================

def evaluate_model(name, y_test, y_pred):
    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    print(f"\n{name} Results:")
    print("R2 Score:", r2)
    print("RMSE:", rmse)

# ===============================
# 11. Model Evaluation
# ===============================

evaluate_model("Linear Regression", y_test, y_pred_lr)
evaluate_model("Ridge Regression", y_test, y_pred_ridge)
evaluate_model("Lasso Regression", y_test, y_pred_lasso)

# ===============================
# 12. Comparison Visualization
# ===============================

models = ['Linear', 'Ridge', 'Lasso']
r2_scores = [
    r2_score(y_test, y_pred_lr),
    r2_score(y_test, y_pred_ridge),
    r2_score(y_test, y_pred_lasso)
]

plt.figure()
plt.bar(models, r2_scores)
plt.title("Model Comparison (R2 Score)")
plt.xlabel("Models")
plt.ylabel("R2 Score")
plt.show()