# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUd27B3Gf5UgbJJEQD307IgZGhd311gZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.cluster.hierarchy as sch
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import AgglomerativeClustering
from google.colab import files

# 1. Load the Dataset
print("Please upload 'Mall_Customers.csv':")
uploaded = files.upload()
df = pd.read_csv('Mall_Customers.csv')

# 2. Preprocessing
# Check for missing values
print("\nMissing values:\n", df.isnull().sum())

# Label Encoding for Gender (Genre)
le = LabelEncoder()
df['Genre'] = le.fit_transform(df['Genre'])

# Selecting features: Annual Income and Spending Score
X = df.iloc[:, [3, 4]].values

# Scaling the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Hierarchical Clustering - Plotting the Dendrogram
plt.figure(figsize=(15, 7))
# 'ward' linkage minimizes the variance of clusters being merged
dendrogram = sch.dendrogram(sch.linkage(X_scaled, method='ward'))
plt.title('Dendrogram for Customer Segmentation')
plt.xlabel('Customers')
plt.ylabel('Euclidean distances')
plt.show()

# 4. Applying Agglomerative Hierarchical Clustering
# Based on the dendrogram, 5 is the optimal number of clusters
hc = AgglomerativeClustering(n_clusters=5, metric='euclidean', linkage='ward')
y_hc = hc.fit_predict(X_scaled)
df['Cluster'] = y_hc

# 5. Visualize the Clusters
plt.figure(figsize=(10, 7))
sns.scatterplot(x=df['Annual Income (k$)'], y=df['Spending Score (1-100)'],
                hue=df['Cluster'], palette='viridis', s=100, style=df['Cluster'])

plt.title('Clusters of Customers (Hierarchical Model)')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend(title='Cluster Group')
plt.grid(True)
plt.show()

# 6. Interpret and Describe the Segments
print("\n--- Cluster Profile Summary (Means) ---")
summary = df.groupby('Cluster')[['Annual Income (k$)', 'Spending Score (1-100)', 'Age']].mean()
print(summary)

print("\n--- Segment Descriptions ---")
descriptions = {
    0: "Careful: High Income, Low Spending",
    1: "Target: High Income, High Spending (Profitable)",
    2: "Standard: Average Income, Average Spending",
    3: "Spendthrifts: Low Income, High Spending",
    4: "Sensible: Low Income, Low Spending"
}
for cluster_id, desc in descriptions.items():
    print(f"Cluster {cluster_id}: {desc}")