# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUd27B3Gf5UgbJJEQD307IgZGhd311gZ
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from google.colab import files

# 1. Load Data
print("Please upload 'UCI_Credit_Card.csv':")
uploaded = files.upload()
df = pd.read_csv('UCI_Credit_Card.csv')

# 2. Preprocessing
# Target variable is 'default.payment.next.month'
features = ['AGE', 'LIMIT_BAL', 'EDUCATION', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']
X = df[features]
y = df['default.payment.next.month']

# For efficiency in Colab, we use a sample
df_sample = df.sample(5000, random_state=42)
X_s = df_sample[features]
y_s = df_sample['default.payment.next.month']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_s, y_s, test_size=0.2, random_state=42)

# Scaling features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 3. Model Building & Comparison
models = {
    'SVM (Linear)': SVC(kernel='linear'),
    'SVM (Poly)': SVC(kernel='poly'),
    'SVM (RBF)': SVC(kernel='rbf'),
    'KNN (k=3)': KNeighborsClassifier(n_neighbors=3),
    'KNN (k=5)': KNeighborsClassifier(n_neighbors=5),
    'KNN (k=7)': KNeighborsClassifier(n_neighbors=7)
}

results = []
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for i, (name, model) in enumerate(models.items()):
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    results.append({'Model': name, 'Accuracy': acc})

    # Plot Confusion Matrix
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[i])
    axes[i].set_title(f'{name}\nAccuracy: {acc:.2%}')
    axes[i].set_xlabel('Predicted')
    axes[i].set_ylabel('Actual')

plt.tight_layout()
plt.show()

# Display Final Comparison
print("\n--- Final Model Comparison ---")
print(pd.DataFrame(results).sort_values(by='Accuracy', ascending=False))