# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUd27B3Gf5UgbJJEQD307IgZGhd311gZ
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# 1. Load Data
print("Please upload 'Admission_Predict_Ver1.1.csv':")
uploaded = files.upload()
df = pd.read_csv('Admission_Predict_Ver1.1.csv')

# 2. Pre-processing
# Drop non-predictive column
df = df.drop(columns=['Serial No.'])

# Create binary target: 1 if Chance of Admit > 0.7, else 0
df['Admitted'] = (df['Chance of Admit '] > 0.7).astype(int)

# Select features (X) and target (y)
X = df.drop(columns=['Chance of Admit ', 'Admitted'])
y = df['Admitted']

# 3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Build Decision Tree Classifier
# Using 'entropy' to measure information gain and limiting depth to prevent overfitting
clf = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=42)
clf.fit(X_train, y_train)

# 5. Evaluate Model
y_pred = clf.predict(X_test)
print("\n--- Accuracy Score ---")
print(f"{accuracy_score(y_test, y_pred):.2%}")

print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

# 6. Visualization
plt.figure(figsize=(20,10))
plot_tree(clf, feature_names=X.columns, class_names=['No', 'Yes'], filled=True, rounded=True)
plt.title("Graduate Admission Decision Tree")
plt.show()

# Heatmap for Confusion Matrix
plt.figure(figsize=(6,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Greens')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()