# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10A0mEDzIItxSmSlSXYFiM4a-DuChgvkh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from google.colab import files

# --- Load Pima Dataset ---
print("Please upload 'diabetes.csv' for the Pima dataset:")
uploaded = files.upload()
pima_df = pd.read_csv('diabetes.csv')

# --- Load UCI Dataset ---
uci_data = load_diabetes()
uci_df = pd.DataFrame(uci_data.data, columns=uci_data.feature_names)
uci_df['target'] = uci_data.target

def perform_univariate(df, name):
    print(f"\n--- Univariate Analysis: {name} ---")
    stats_df = pd.DataFrame({
        'Mean': df.mean(),
        'Median': df.median(),
        'Mode': df.mode().iloc[0],
        'Variance': df.var(),
        'Std Dev': df.std(),
        'Skewness': df.skew(),
        'Kurtosis': df.kurtosis(),
        'Frequency (Count)': df.count()
    })
    return stats_df

pima_stats = perform_univariate(pima_df, "Pima Indians")
uci_stats = perform_univariate(uci_df, "UCI Diabetes")

print(pima_stats)
print(uci_stats)

# --- Pima Bivariate ---
# Linear: BMI vs Glucose
X_p_lin = pima_df[['BMI']]
y_p_lin = pima_df['Glucose']
lin_pima = LinearRegression().fit(X_p_lin, y_p_lin)

# Logistic: Glucose vs Outcome
X_p_log = pima_df[['Glucose']]
y_p_log = pima_df['Outcome']
log_pima = LogisticRegression().fit(X_p_log, y_p_log)

# --- UCI Bivariate ---
# Linear: bmi vs target
X_u_lin = uci_df[['bmi']]
y_u_lin = uci_df['target']
lin_uci = LinearRegression().fit(X_u_lin, y_u_lin)

# Logistic: bmi vs target_binary (High/Low progression)
uci_df['target_bin'] = (uci_df['target'] > uci_df['target'].median()).astype(int)
X_u_log = uci_df[['bmi']]
y_u_log = uci_df['target_bin']
log_uci = LogisticRegression().fit(X_u_log, y_u_log)

print(f"Pima: Linear R2 = {lin_pima.score(X_p_lin, y_p_lin):.4f}, Logistic Acc = {log_pima.score(X_p_log, y_p_log):.4f}")
print(f"UCI: Linear R2 = {lin_uci.score(X_u_lin, y_u_lin):.4f}, Logistic Acc = {log_uci.score(X_u_log, y_u_log):.4f}")

# Pima Multiple Linear (Target: Glucose)
X_p_mult = pima_df.drop(columns=['Outcome', 'Glucose'])
y_p_mult = pima_df['Glucose']
mult_pima = LinearRegression().fit(X_p_mult, y_p_mult)

# UCI Multiple Linear (Target: progression measure)
X_u_mult = uci_df.drop(columns=['target', 'target_bin'])
y_u_mult = uci_df['target']
mult_uci = LinearRegression().fit(X_u_mult, y_u_mult)

print(f"Pima Multiple Regression R2: {mult_pima.score(X_p_mult, y_p_mult):.4f}")
print(f"UCI Multiple Regression R2: {mult_uci.score(X_u_mult, y_u_mult):.4f}")

plt.figure(figsize=(14, 10))

# Univariate: Pima Glucose
plt.subplot(2, 2, 1)
sns.histplot(pima_df['Glucose'], kde=True, color='skyblue')
plt.title('Pima: Glucose Distribution')

# Univariate: UCI Target
plt.subplot(2, 2, 2)
sns.histplot(uci_df['target'], kde=True, color='salmon')
plt.title('UCI: Disease Progression Distribution')

# Bivariate: Pima Linear
plt.subplot(2, 2, 3)
sns.regplot(x='BMI', y='Glucose', data=pima_df, line_kws={'color':'red'})
plt.title('Pima: BMI vs Glucose')

# Bivariate: UCI Linear
plt.subplot(2, 2, 4)
sns.regplot(x='bmi', y='target', data=uci_df, line_kws={'color':'red'})
plt.title('UCI: BMI vs Progression')

plt.tight_layout()
plt.show()

comparison = pd.DataFrame({
    'Metric': ['Linear R2 (BMI)', 'Logistic Acc', 'Multiple R2 (All)'],
    'Pima Dataset': [lin_pima.score(X_p_lin, y_p_lin), log_pima.score(X_p_log, y_p_log), mult_pima.score(X_p_mult, y_p_mult)],
    'UCI Dataset': [lin_uci.score(X_u_lin, y_u_lin), log_uci.score(X_u_log, y_u_log), mult_uci.score(X_u_mult, y_u_mult)]
})
print("\n--- Summary Comparison ---")
print(comparison)