# -*- coding: utf-8 -*-
"""Assignment No 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-yFnUHP_wKXcvnc4UC7w-gyPGQkbFw5

Name:Tanvi Sanjay Salagare  Roll no:20  PRN:1252090020  Div:SEDA CSE(AI)  Batch:B1

#!/bin/bash
curl -L -o ~/Downloads/house-price-prediction-dataset.zip\
  https://www.kaggle.com/api/v1/datasets/download/zafarali27/house-price-prediction-dataset

Import Required Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""Read Data from Different Formats
Read CSV file
"""

df = pd.read_csv('House Price Prediction Dataset.csv')
df.head()

"""Find Shape of Data"""

df.shape

"""Find Missing Values"""

df.isnull().sum()

df.isnull().any()

"""Find Data Type of Each Column"""

df.dtypes

df.info()

"""Finding Out Zero’s

Count zero values column-wise
"""

(df == 0).sum()

"""Total zero values"""

(df == 0).sum().sum()

"""Indexing and Selecting Data

Check actual column names
"""

df.columns

df['Price']

df['Price'] = df['Price'].astype(float)

df.columns = df.columns.str.lower()
df.columns

df['price'] = df['price'].astype(float)

"""datatype conversions

Check unique values
"""

df['garage'].unique()

# Clean column names (recommended)
df.columns = df.columns.str.lower()

# Convert categorical 'garage' column to numeric
df['garage'] = df['garage'].map({'Yes': 1, 'No': 0})

# Datatype conversion (long to short)
df['area'] = df['area'].astype('int32')
df['bedrooms'] = df['bedrooms'].astype('int8')
df['bathrooms'] = df['bathrooms'].astype('int8')
df['floors'] = df['floors'].astype('int8')
df['garage'] = df['garage'].astype('int8')
df['price'] = df['price'].astype(float)

# Check final datatypes
df.dtypes

"""Select multiple columns"""

df[['bedrooms', 'area']]

"""Select rows using index"""

df.iloc[0:5]

"""Sorting Data

Sort by price (ascending)
"""

df.sort_values(by='price')

"""Sort by area (descending)"""

df.sort_values(by='area', ascending=False)

"""Describe Attributes of Data"""

df.describe()

"""Checking Data Types of Each Column"""

df.info()

"""Counting Unique Values

Count unique values per column
"""

df.nunique()

"""View unique values of a column"""

df['bedrooms'].unique()

"""Format of Each Column"""

df.dtypes

"""Converting Variable Data Types"""

df['area'] = df['area'].astype('int32')
df['bedrooms'] = df['bedrooms'].astype('int8')
df['bathrooms'] = df['bathrooms'].astype('int8')

df.dtypes

"""Create Student DataFrame"""

student_data = {
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['A', 'B', 'C', 'D', 'E'],
    'Age': [20, 21, 19, 22, 20],
    'Branch': ['CSE', 'IT', 'CSE', 'ECE', 'AI'],
    'Marks': [85, 90, 78, 88, 92]
}

df_student = pd.DataFrame(student_data)
df_student

"""Shape of Student Data"""

df_student.shape

"""Missing Values"""

df_student.isnull().sum()

"""Data Types"""

df_student.dtypes

"""Describe Student Data"""

df_student.describe()

"""Unique Values"""

df_student.nunique()

"""Data Type Conversion"""

df_student['Age'] = df_student['Age'].astype('int8')
df_student['Marks'] = df_student['Marks'].astype('int8')

df_student.dtypes

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("House Price Prediction Dataset.csv")

print(df.head())   # check dataset

df.isnull().sum().plot(kind='bar')
plt.show()

plt.figure(figsize=(8,5))
df.isnull().sum().plot(kind='bar')
plt.title("Missing Values per Column")
plt.xlabel("Columns")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

df.hist(figsize=(12,10))
plt.suptitle("Histogram of Numerical Features")
plt.show()

plt.figure(figsize=(12,6))
sns.boxplot(data=df.select_dtypes(include=['int64','float64']))
plt.title("Boxplot for Outliers")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(6,4))
sns.barplot(x=df['Bedrooms'], y=df['Price'])
plt.title("Bedrooms vs Price")
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(x=df['Area'], y=df['Price'])
plt.title("Area vs Price")
plt.show()