# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUd27B3Gf5UgbJJEQD307IgZGhd311gZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression, LogisticRegression
from google.colab import files

# --- 1. Load Datasets ---
print("Please upload 'diabetes.csv':")
uploaded = files.upload()
pima_df = pd.read_csv('temperatures.csv')

uci_data = load_diabetes()
uci_df = pd.DataFrame(uci_data.data, columns=uci_data.feature_names)
uci_df['target'] = uci_data.target

# --- 2. Univariate Analysis ---
def get_stats(df):
    return pd.DataFrame({
        'Mean': df.mean(), 'Median': df.median(), 'Mode': df.mode().iloc[0],
        'Var': df.var(), 'Std': df.std(), 'Skew': df.skew(), 'Kurt': df.kurtosis()
    })

print("\nPima Univariate Stats:\n", get_stats(pima_df))

# --- 3. Bivariate & Multiple Regression ---
# Pima: Predict Outcome using Glucose (Logistic)
X_p = pima_df[['Glucose']]
y_p = pima_df['Outcome']
model_p = LogisticRegression().fit(X_p, y_p)
print(f"Pima Logistic Accuracy: {model_p.score(X_p, y_p):.4f}")

# UCI: Multiple Linear Regression
X_u = uci_df.drop(columns=['target'])
y_u = uci_df['target']
model_u = LinearRegression().fit(X_u, y_u)
print(f"UCI Multiple Regression R2: {model_u.score(X_u, y_u):.4f}")