# -*- coding: utf-8 -*-
"""Assignment 2 aiml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAK3NCp8xhwmDaSgAcLgIVXs9Lo_z26P
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("train.csv")
df.head()

df.shape

df.info()

df.nunique()

df.describe()

numerical_df = df.select_dtypes(include=[np.number])

for column in numerical_df.columns:
    print(f"Feature : {column}")
    print(f"Minimum Value      : {numerical_df[column].min()}")
    print(f"Maximum Value      : {numerical_df[column].max()}")
    print(f"Mean               : {numerical_df[column].mean()}")
    print(f"Median             : {numerical_df[column].median()}")
    print(f"Variance           : {numerical_df[column].var()}")
    print(f"Standard Deviation : {numerical_df[column].std()}")
    print("Percentiles:")
    print(f" 25% : {numerical_df[column].quantile(0.25)}")
    print(f" 50% : {numerical_df[column].quantile(0.50)}")
    print(f" 75% : {numerical_df[column].quantile(0.75)}")
    print("-"*40)

numerical_df.hist(bins=10, figsize=(12,8))
plt.suptitle("Feature Distributions using Histogram")
plt.show()

df.isnull().sum()

df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.drop(['Cabin', 'Name', 'Ticket'], axis=1, inplace=True)

df.drop_duplicates(inplace=True)

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

df = pd.get_dummies(df, columns=['Embarked'])

df['Fare'] = (df['Fare'] - df['Fare'].min()) / (df['Fare'].max() - df['Fare'].min())

df_part1 = df.iloc[:500]
df_part2 = df.iloc[500:]

integrated_df = pd.concat([df_part1, df_part2])
integrated_df.head()

from sklearn.model_selection import train_test_split

X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

import pandas as pd

10, 20, 40, 69, 10, 30, 40, 89, 42

data = [10, 20, 40, 69, 10, 30, 40, 89, 42]

df = pd.DataFrame(data, columns=['Values'])
df

df['Values'].mean()

df['Values'].max()

df['Values'].min()

df['Values'].median()

df['Values'].mode()

df['Values'].var()

df['Values'].std()

df['Values'].max() - df['Values'].min()

df['Values'].quantile(0.25)   # 25%
df['Values'].quantile(0.50)   # 50% (Median)
df['Values'].quantile(0.75)   # 75%

df.describe()

