# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uL9Bs_GzlDHsH7NUAOb_PEqJFgqohmD
"""

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("Housing.csv")

# Display basic info (Assignment 1/2 type work)
print("First 5 rows:\n", df.head())
print("\nDataset Info:\n")
print(df.info())
print("\nStatistical Summary:\n", df.describe())

# -------------------------------
# 1. SCATTER PLOT
# Example: area vs price
# -------------------------------
plt.figure()
plt.scatter(df['area'], df['price'])
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Scatter Plot: Area vs Price")
plt.show()

# -------------------------------
# 2. BAR PLOT
# Example: furnishingstatus count
# -------------------------------
plt.figure()
df['furnishingstatus'].value_counts().plot(kind='bar')
plt.xlabel("Furnishing Status")
plt.ylabel("Count")
plt.title("Bar Plot: Furnishing Status Count")
plt.show()

# -------------------------------
# 3. BOX PLOT
# Example: price distribution
# -------------------------------
plt.figure()
sns.boxplot(y=df['price'])
plt.title("Box Plot: Price Distribution")
plt.show()

# -------------------------------
# 4. PIE CHART
# Example: mainroad distribution
# -------------------------------
plt.figure()
df['mainroad'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.title("Pie Chart: Main Road Access")
plt.ylabel("")
plt.show()

# -------------------------------
# 5. LINE CHART
# Example: sorted area vs price
# -------------------------------
df_sorted = df.sort_values(by='area')

plt.figure()
plt.plot(df_sorted['area'], df_sorted['price'])
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Line Chart: Area vs Price")
plt.show()

from google.colab import drive
drive.mount('/content/drive')